/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IROSCAFactory } from "./IROSCAFactory";
export type { ROSCAAnalytics } from "./ROSCAAnalytics";
