/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IROSCAFactoryInterface extends utils.Interface {
  functions: {
    "PYUSD()": FunctionFragment;
    "circles(uint256)": FunctionFragment;
    "circlesByCountry(string)": FunctionFragment;
    "totalCircles()": FunctionFragment;
    "totalPlatformRevenue()": FunctionFragment;
    "userCircles(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "PYUSD"
      | "circles"
      | "circlesByCountry"
      | "totalCircles"
      | "totalPlatformRevenue"
      | "userCircles"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "PYUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "circles",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "circlesByCountry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCircles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlatformRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userCircles",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "PYUSD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "circles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "circlesByCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCircles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPlatformRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCircles",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IROSCAFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IROSCAFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PYUSD(overrides?: CallOverrides): Promise<[string]>;

    circles(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    circlesByCountry(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    totalCircles(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalPlatformRevenue(overrides?: CallOverrides): Promise<[BigNumber]>;

    userCircles(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;
  };

  PYUSD(overrides?: CallOverrides): Promise<string>;

  circles(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  circlesByCountry(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  totalCircles(overrides?: CallOverrides): Promise<BigNumber>;

  totalPlatformRevenue(overrides?: CallOverrides): Promise<BigNumber>;

  userCircles(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  callStatic: {
    PYUSD(overrides?: CallOverrides): Promise<string>;

    circles(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    circlesByCountry(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    totalCircles(overrides?: CallOverrides): Promise<BigNumber>;

    totalPlatformRevenue(overrides?: CallOverrides): Promise<BigNumber>;

    userCircles(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;
  };

  filters: {};

  estimateGas: {
    PYUSD(overrides?: CallOverrides): Promise<BigNumber>;

    circles(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    circlesByCountry(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalCircles(overrides?: CallOverrides): Promise<BigNumber>;

    totalPlatformRevenue(overrides?: CallOverrides): Promise<BigNumber>;

    userCircles(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PYUSD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    circles(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    circlesByCountry(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalCircles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalPlatformRevenue(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userCircles(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
