/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as roscaCircleSol from "./ROSCACircle.sol";
export type { roscaCircleSol };
import type * as simpleKycVerifierSol from "./SimpleKYCVerifier.sol";
export type { simpleKycVerifierSol };
import type * as yieldManagerSol from "./YieldManager.sol";
export type { yieldManagerSol };
export type { MockERC20 } from "./MockERC20";
export type { ROSCAFactory } from "./ROSCAFactory";
