/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace ROSCACircle {
  export type CircleParamsStruct = {
    monthlyAmount: PromiseOrValue<BigNumberish>;
    maxMembers: PromiseOrValue<BigNumberish>;
    duration: PromiseOrValue<BigNumberish>;
    country: PromiseOrValue<string>;
    minAge: PromiseOrValue<BigNumberish>;
    maxAge: PromiseOrValue<BigNumberish>;
    platformFeePercent: PromiseOrValue<BigNumberish>;
  };

  export type CircleParamsStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    monthlyAmount: BigNumber;
    maxMembers: BigNumber;
    duration: BigNumber;
    country: string;
    minAge: BigNumber;
    maxAge: BigNumber;
    platformFeePercent: BigNumber;
  };

  export type MemberStruct = {
    memberAddress: PromiseOrValue<string>;
    hasContributedCurrentRound: PromiseOrValue<boolean>;
    hasReceivedPayout: PromiseOrValue<boolean>;
    reputationScore: PromiseOrValue<BigNumberish>;
    joinedAt: PromiseOrValue<BigNumberish>;
    totalContributions: PromiseOrValue<BigNumberish>;
    missedContributions: PromiseOrValue<BigNumberish>;
    nationality: PromiseOrValue<string>;
    currentAge: PromiseOrValue<BigNumberish>;
  };

  export type MemberStructOutput = [
    string,
    boolean,
    boolean,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber
  ] & {
    memberAddress: string;
    hasContributedCurrentRound: boolean;
    hasReceivedPayout: boolean;
    reputationScore: BigNumber;
    joinedAt: BigNumber;
    totalContributions: BigNumber;
    missedContributions: BigNumber;
    nationality: string;
    currentAge: BigNumber;
  };

  export type RoundInfoStruct = {
    roundNumber: PromiseOrValue<BigNumberish>;
    recipient: PromiseOrValue<string>;
    totalCollected: PromiseOrValue<BigNumberish>;
    payoutAmount: PromiseOrValue<BigNumberish>;
    contributorCount: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    isCompleted: PromiseOrValue<boolean>;
    yieldEarned: PromiseOrValue<BigNumberish>;
  };

  export type RoundInfoStructOutput = [
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    BigNumber
  ] & {
    roundNumber: BigNumber;
    recipient: string;
    totalCollected: BigNumber;
    payoutAmount: BigNumber;
    contributorCount: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    isCompleted: boolean;
    yieldEarned: BigNumber;
  };
}

export interface ROSCACircleInterface extends utils.Interface {
  functions: {
    "PYUSD()": FunctionFragment;
    "addYield(uint256,string)": FunctionFragment;
    "circleParams()": FunctionFragment;
    "circleStartTime()": FunctionFragment;
    "contributionTimestamps(uint256,address)": FunctionFragment;
    "currentRound()": FunctionFragment;
    "distributePayout()": FunctionFragment;
    "emergencyExit()": FunctionFragment;
    "emergencyPause()": FunctionFragment;
    "emergencyPaused()": FunctionFragment;
    "emergencyUnpause()": FunctionFragment;
    "factory()": FunctionFragment;
    "getAllMembers()": FunctionFragment;
    "getAllRounds()": FunctionFragment;
    "getCircleInfo()": FunctionFragment;
    "getContributionStatus(address)": FunctionFragment;
    "getCurrentRoundInfo()": FunctionFragment;
    "getMemberInfo(address)": FunctionFragment;
    "hasReceivedPayout(address)": FunctionFragment;
    "isActive()": FunctionFragment;
    "isCompleted()": FunctionFragment;
    "isMember(address)": FunctionFragment;
    "joinCircle()": FunctionFragment;
    "kycVerifier()": FunctionFragment;
    "makeContribution()": FunctionFragment;
    "memberIndex(address)": FunctionFragment;
    "members(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "roundContributions(uint256,address)": FunctionFragment;
    "rounds(uint256)": FunctionFragment;
    "totalFeesCollected()": FunctionFragment;
    "totalYieldEarned()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "PYUSD"
      | "addYield"
      | "circleParams"
      | "circleStartTime"
      | "contributionTimestamps"
      | "currentRound"
      | "distributePayout"
      | "emergencyExit"
      | "emergencyPause"
      | "emergencyPaused"
      | "emergencyUnpause"
      | "factory"
      | "getAllMembers"
      | "getAllRounds"
      | "getCircleInfo"
      | "getContributionStatus"
      | "getCurrentRoundInfo"
      | "getMemberInfo"
      | "hasReceivedPayout"
      | "isActive"
      | "isCompleted"
      | "isMember"
      | "joinCircle"
      | "kycVerifier"
      | "makeContribution"
      | "memberIndex"
      | "members"
      | "owner"
      | "renounceOwnership"
      | "roundContributions"
      | "rounds"
      | "totalFeesCollected"
      | "totalYieldEarned"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "PYUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addYield",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "circleParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "circleStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributionTimestamps",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "currentRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributePayout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyExit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyUnpause",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRounds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCircleInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContributionStatus",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRoundInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReceivedPayout",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isCompleted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "joinCircle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "kycVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "makeContribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "memberIndex",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "roundContributions",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalYieldEarned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "PYUSD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addYield", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "circleParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "circleStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributionTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllRounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCircleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRoundInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReceivedPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinCircle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kycVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roundContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalYieldEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "CircleCompleted(uint256,uint256,uint256)": EventFragment;
    "CircleStarted(uint256,uint256)": EventFragment;
    "ContributionMade(address,uint256,uint256,uint256)": EventFragment;
    "EmergencyExit(address,uint256,uint256)": EventFragment;
    "MemberJoined(address,uint256,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PayoutDistributed(address,uint256,uint256,uint256)": EventFragment;
    "ReputationUpdated(address,uint256)": EventFragment;
    "YieldEarned(uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CircleCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CircleStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributionMade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyExit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MemberJoined"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PayoutDistributed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReputationUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "YieldEarned"): EventFragment;
}

export interface CircleCompletedEventObject {
  totalRounds: BigNumber;
  totalVolume: BigNumber;
  totalYield: BigNumber;
}
export type CircleCompletedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  CircleCompletedEventObject
>;

export type CircleCompletedEventFilter = TypedEventFilter<CircleCompletedEvent>;

export interface CircleStartedEventObject {
  startTime: BigNumber;
  expectedEndTime: BigNumber;
}
export type CircleStartedEvent = TypedEvent<
  [BigNumber, BigNumber],
  CircleStartedEventObject
>;

export type CircleStartedEventFilter = TypedEventFilter<CircleStartedEvent>;

export interface ContributionMadeEventObject {
  contributor: string;
  amount: BigNumber;
  round: BigNumber;
  timestamp: BigNumber;
}
export type ContributionMadeEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  ContributionMadeEventObject
>;

export type ContributionMadeEventFilter =
  TypedEventFilter<ContributionMadeEvent>;

export interface EmergencyExitEventObject {
  member: string;
  refundAmount: BigNumber;
  penalty: BigNumber;
}
export type EmergencyExitEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  EmergencyExitEventObject
>;

export type EmergencyExitEventFilter = TypedEventFilter<EmergencyExitEvent>;

export interface MemberJoinedEventObject {
  member: string;
  memberCount: BigNumber;
  nationality: string;
}
export type MemberJoinedEvent = TypedEvent<
  [string, BigNumber, string],
  MemberJoinedEventObject
>;

export type MemberJoinedEventFilter = TypedEventFilter<MemberJoinedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PayoutDistributedEventObject {
  recipient: string;
  amount: BigNumber;
  round: BigNumber;
  fees: BigNumber;
}
export type PayoutDistributedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  PayoutDistributedEventObject
>;

export type PayoutDistributedEventFilter =
  TypedEventFilter<PayoutDistributedEvent>;

export interface ReputationUpdatedEventObject {
  member: string;
  newScore: BigNumber;
}
export type ReputationUpdatedEvent = TypedEvent<
  [string, BigNumber],
  ReputationUpdatedEventObject
>;

export type ReputationUpdatedEventFilter =
  TypedEventFilter<ReputationUpdatedEvent>;

export interface YieldEarnedEventObject {
  amount: BigNumber;
  source: string;
}
export type YieldEarnedEvent = TypedEvent<
  [BigNumber, string],
  YieldEarnedEventObject
>;

export type YieldEarnedEventFilter = TypedEventFilter<YieldEarnedEvent>;

export interface ROSCACircle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ROSCACircleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PYUSD(overrides?: CallOverrides): Promise<[string]>;

    addYield(
      amount: PromiseOrValue<BigNumberish>,
      source: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    circleParams(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        monthlyAmount: BigNumber;
        maxMembers: BigNumber;
        duration: BigNumber;
        country: string;
        minAge: BigNumber;
        maxAge: BigNumber;
        platformFeePercent: BigNumber;
      }
    >;

    circleStartTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    contributionTimestamps(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    currentRound(overrides?: CallOverrides): Promise<[BigNumber]>;

    distributePayout(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyExit(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    emergencyPaused(overrides?: CallOverrides): Promise<[boolean]>;

    emergencyUnpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getAllMembers(
      overrides?: CallOverrides
    ): Promise<[ROSCACircle.MemberStructOutput[]]>;

    getAllRounds(
      overrides?: CallOverrides
    ): Promise<[ROSCACircle.RoundInfoStructOutput[]]>;

    getCircleInfo(
      overrides?: CallOverrides
    ): Promise<
      [
        ROSCACircle.CircleParamsStructOutput,
        BigNumber,
        BigNumber,
        boolean,
        boolean
      ] & {
        params: ROSCACircle.CircleParamsStructOutput;
        memberCount: BigNumber;
        round: BigNumber;
        active: boolean;
        completed: boolean;
      }
    >;

    getContributionStatus(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, boolean, BigNumber] & {
        hasContributed: boolean;
        deadline: BigNumber;
        canContribute: boolean;
        contributionTime: BigNumber;
      }
    >;

    getCurrentRoundInfo(
      overrides?: CallOverrides
    ): Promise<[ROSCACircle.RoundInfoStructOutput]>;

    getMemberInfo(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[ROSCACircle.MemberStructOutput]>;

    hasReceivedPayout(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isActive(overrides?: CallOverrides): Promise<[boolean]>;

    isCompleted(overrides?: CallOverrides): Promise<[boolean]>;

    isMember(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    joinCircle(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    kycVerifier(overrides?: CallOverrides): Promise<[string]>;

    makeContribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    memberIndex(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    members(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        boolean,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ] & {
        memberAddress: string;
        hasContributedCurrentRound: boolean;
        hasReceivedPayout: boolean;
        reputationScore: BigNumber;
        joinedAt: BigNumber;
        totalContributions: BigNumber;
        missedContributions: BigNumber;
        nationality: string;
        currentAge: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    roundContributions(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    rounds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        BigNumber
      ] & {
        roundNumber: BigNumber;
        recipient: string;
        totalCollected: BigNumber;
        payoutAmount: BigNumber;
        contributorCount: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        isCompleted: boolean;
        yieldEarned: BigNumber;
      }
    >;

    totalFeesCollected(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalYieldEarned(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  PYUSD(overrides?: CallOverrides): Promise<string>;

  addYield(
    amount: PromiseOrValue<BigNumberish>,
    source: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  circleParams(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      monthlyAmount: BigNumber;
      maxMembers: BigNumber;
      duration: BigNumber;
      country: string;
      minAge: BigNumber;
      maxAge: BigNumber;
      platformFeePercent: BigNumber;
    }
  >;

  circleStartTime(overrides?: CallOverrides): Promise<BigNumber>;

  contributionTimestamps(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  currentRound(overrides?: CallOverrides): Promise<BigNumber>;

  distributePayout(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyExit(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyPause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  emergencyPaused(overrides?: CallOverrides): Promise<boolean>;

  emergencyUnpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  getAllMembers(
    overrides?: CallOverrides
  ): Promise<ROSCACircle.MemberStructOutput[]>;

  getAllRounds(
    overrides?: CallOverrides
  ): Promise<ROSCACircle.RoundInfoStructOutput[]>;

  getCircleInfo(
    overrides?: CallOverrides
  ): Promise<
    [
      ROSCACircle.CircleParamsStructOutput,
      BigNumber,
      BigNumber,
      boolean,
      boolean
    ] & {
      params: ROSCACircle.CircleParamsStructOutput;
      memberCount: BigNumber;
      round: BigNumber;
      active: boolean;
      completed: boolean;
    }
  >;

  getContributionStatus(
    member: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, boolean, BigNumber] & {
      hasContributed: boolean;
      deadline: BigNumber;
      canContribute: boolean;
      contributionTime: BigNumber;
    }
  >;

  getCurrentRoundInfo(
    overrides?: CallOverrides
  ): Promise<ROSCACircle.RoundInfoStructOutput>;

  getMemberInfo(
    member: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ROSCACircle.MemberStructOutput>;

  hasReceivedPayout(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isActive(overrides?: CallOverrides): Promise<boolean>;

  isCompleted(overrides?: CallOverrides): Promise<boolean>;

  isMember(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  joinCircle(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  kycVerifier(overrides?: CallOverrides): Promise<string>;

  makeContribution(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  memberIndex(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  members(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      boolean,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber
    ] & {
      memberAddress: string;
      hasContributedCurrentRound: boolean;
      hasReceivedPayout: boolean;
      reputationScore: BigNumber;
      joinedAt: BigNumber;
      totalContributions: BigNumber;
      missedContributions: BigNumber;
      nationality: string;
      currentAge: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  roundContributions(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  rounds(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean,
      BigNumber
    ] & {
      roundNumber: BigNumber;
      recipient: string;
      totalCollected: BigNumber;
      payoutAmount: BigNumber;
      contributorCount: BigNumber;
      startTime: BigNumber;
      endTime: BigNumber;
      isCompleted: boolean;
      yieldEarned: BigNumber;
    }
  >;

  totalFeesCollected(overrides?: CallOverrides): Promise<BigNumber>;

  totalYieldEarned(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    PYUSD(overrides?: CallOverrides): Promise<string>;

    addYield(
      amount: PromiseOrValue<BigNumberish>,
      source: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    circleParams(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        monthlyAmount: BigNumber;
        maxMembers: BigNumber;
        duration: BigNumber;
        country: string;
        minAge: BigNumber;
        maxAge: BigNumber;
        platformFeePercent: BigNumber;
      }
    >;

    circleStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    contributionTimestamps(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentRound(overrides?: CallOverrides): Promise<BigNumber>;

    distributePayout(overrides?: CallOverrides): Promise<void>;

    emergencyExit(overrides?: CallOverrides): Promise<void>;

    emergencyPause(overrides?: CallOverrides): Promise<void>;

    emergencyPaused(overrides?: CallOverrides): Promise<boolean>;

    emergencyUnpause(overrides?: CallOverrides): Promise<void>;

    factory(overrides?: CallOverrides): Promise<string>;

    getAllMembers(
      overrides?: CallOverrides
    ): Promise<ROSCACircle.MemberStructOutput[]>;

    getAllRounds(
      overrides?: CallOverrides
    ): Promise<ROSCACircle.RoundInfoStructOutput[]>;

    getCircleInfo(
      overrides?: CallOverrides
    ): Promise<
      [
        ROSCACircle.CircleParamsStructOutput,
        BigNumber,
        BigNumber,
        boolean,
        boolean
      ] & {
        params: ROSCACircle.CircleParamsStructOutput;
        memberCount: BigNumber;
        round: BigNumber;
        active: boolean;
        completed: boolean;
      }
    >;

    getContributionStatus(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, boolean, BigNumber] & {
        hasContributed: boolean;
        deadline: BigNumber;
        canContribute: boolean;
        contributionTime: BigNumber;
      }
    >;

    getCurrentRoundInfo(
      overrides?: CallOverrides
    ): Promise<ROSCACircle.RoundInfoStructOutput>;

    getMemberInfo(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ROSCACircle.MemberStructOutput>;

    hasReceivedPayout(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isActive(overrides?: CallOverrides): Promise<boolean>;

    isCompleted(overrides?: CallOverrides): Promise<boolean>;

    isMember(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    joinCircle(overrides?: CallOverrides): Promise<void>;

    kycVerifier(overrides?: CallOverrides): Promise<string>;

    makeContribution(overrides?: CallOverrides): Promise<void>;

    memberIndex(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    members(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        boolean,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ] & {
        memberAddress: string;
        hasContributedCurrentRound: boolean;
        hasReceivedPayout: boolean;
        reputationScore: BigNumber;
        joinedAt: BigNumber;
        totalContributions: BigNumber;
        missedContributions: BigNumber;
        nationality: string;
        currentAge: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    roundContributions(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rounds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        BigNumber
      ] & {
        roundNumber: BigNumber;
        recipient: string;
        totalCollected: BigNumber;
        payoutAmount: BigNumber;
        contributorCount: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        isCompleted: boolean;
        yieldEarned: BigNumber;
      }
    >;

    totalFeesCollected(overrides?: CallOverrides): Promise<BigNumber>;

    totalYieldEarned(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CircleCompleted(uint256,uint256,uint256)"(
      totalRounds?: null,
      totalVolume?: null,
      totalYield?: null
    ): CircleCompletedEventFilter;
    CircleCompleted(
      totalRounds?: null,
      totalVolume?: null,
      totalYield?: null
    ): CircleCompletedEventFilter;

    "CircleStarted(uint256,uint256)"(
      startTime?: null,
      expectedEndTime?: null
    ): CircleStartedEventFilter;
    CircleStarted(
      startTime?: null,
      expectedEndTime?: null
    ): CircleStartedEventFilter;

    "ContributionMade(address,uint256,uint256,uint256)"(
      contributor?: PromiseOrValue<string> | null,
      amount?: null,
      round?: null,
      timestamp?: null
    ): ContributionMadeEventFilter;
    ContributionMade(
      contributor?: PromiseOrValue<string> | null,
      amount?: null,
      round?: null,
      timestamp?: null
    ): ContributionMadeEventFilter;

    "EmergencyExit(address,uint256,uint256)"(
      member?: PromiseOrValue<string> | null,
      refundAmount?: null,
      penalty?: null
    ): EmergencyExitEventFilter;
    EmergencyExit(
      member?: PromiseOrValue<string> | null,
      refundAmount?: null,
      penalty?: null
    ): EmergencyExitEventFilter;

    "MemberJoined(address,uint256,string)"(
      member?: PromiseOrValue<string> | null,
      memberCount?: null,
      nationality?: null
    ): MemberJoinedEventFilter;
    MemberJoined(
      member?: PromiseOrValue<string> | null,
      memberCount?: null,
      nationality?: null
    ): MemberJoinedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PayoutDistributed(address,uint256,uint256,uint256)"(
      recipient?: PromiseOrValue<string> | null,
      amount?: null,
      round?: null,
      fees?: null
    ): PayoutDistributedEventFilter;
    PayoutDistributed(
      recipient?: PromiseOrValue<string> | null,
      amount?: null,
      round?: null,
      fees?: null
    ): PayoutDistributedEventFilter;

    "ReputationUpdated(address,uint256)"(
      member?: PromiseOrValue<string> | null,
      newScore?: null
    ): ReputationUpdatedEventFilter;
    ReputationUpdated(
      member?: PromiseOrValue<string> | null,
      newScore?: null
    ): ReputationUpdatedEventFilter;

    "YieldEarned(uint256,string)"(
      amount?: null,
      source?: null
    ): YieldEarnedEventFilter;
    YieldEarned(amount?: null, source?: null): YieldEarnedEventFilter;
  };

  estimateGas: {
    PYUSD(overrides?: CallOverrides): Promise<BigNumber>;

    addYield(
      amount: PromiseOrValue<BigNumberish>,
      source: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    circleParams(overrides?: CallOverrides): Promise<BigNumber>;

    circleStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    contributionTimestamps(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentRound(overrides?: CallOverrides): Promise<BigNumber>;

    distributePayout(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyExit(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    emergencyPaused(overrides?: CallOverrides): Promise<BigNumber>;

    emergencyUnpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getAllMembers(overrides?: CallOverrides): Promise<BigNumber>;

    getAllRounds(overrides?: CallOverrides): Promise<BigNumber>;

    getCircleInfo(overrides?: CallOverrides): Promise<BigNumber>;

    getContributionStatus(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentRoundInfo(overrides?: CallOverrides): Promise<BigNumber>;

    getMemberInfo(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasReceivedPayout(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isActive(overrides?: CallOverrides): Promise<BigNumber>;

    isCompleted(overrides?: CallOverrides): Promise<BigNumber>;

    isMember(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    joinCircle(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    kycVerifier(overrides?: CallOverrides): Promise<BigNumber>;

    makeContribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    memberIndex(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    members(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    roundContributions(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rounds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalFeesCollected(overrides?: CallOverrides): Promise<BigNumber>;

    totalYieldEarned(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PYUSD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addYield(
      amount: PromiseOrValue<BigNumberish>,
      source: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    circleParams(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    circleStartTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contributionTimestamps(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentRound(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    distributePayout(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyExit(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    emergencyPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    emergencyUnpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllMembers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllRounds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCircleInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getContributionStatus(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentRoundInfo(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMemberInfo(
      member: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasReceivedPayout(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isActive(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isCompleted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isMember(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    joinCircle(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    kycVerifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    makeContribution(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    memberIndex(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    members(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    roundContributions(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rounds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalFeesCollected(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalYieldEarned(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
