/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKYCVerifier__factory } from "./IKYCVerifier__factory";
export { ROSCACircle__factory } from "./ROSCACircle__factory";
