/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IROSCACircle,
  IROSCACircleInterface,
} from "../../../contracts/YieldManager.sol/IROSCACircle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "source",
        type: "string",
      },
    ],
    name: "addYield",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IROSCACircle__factory {
  static readonly abi = _abi;
  static createInterface(): IROSCACircleInterface {
    return new utils.Interface(_abi) as IROSCACircleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IROSCACircle {
    return new Contract(address, _abi, signerOrProvider) as IROSCACircle;
  }
}
